###############################################################################
# preprocess/13_build_siec_to_ipcc_mapping.R
#
# PURPOSE
#   Build SIEC -> IPCC fuel category mapping used to translate
#   Eurostat/energy-balance fuels into IPCC categories.
#
# HOW THIS LIST WAS PRODUCED
#   The IPCC fuel assignments were generated by prompting an LLM (Claude
#   Opus 4.6, Anthropic) in a fresh conversation with no project-specific
#   context.  The SIEC codes and names were taken verbatim from the
#   Eurostat SIEC codelist (SIEC Version 1.0, as implemented by Eurostat;
#   source: https://dd.eionet.europa.eu/vocabulary/eurostat/siec/view)
#   and embedded in the prompt so the LLM only had to supply the IPCC
#   mapping — not recall the SIEC codes from memory.
#
#   The exact prompt is reproduced below so that other researchers can
#   verify or reproduce the mapping independently.
#
# MODEL
#   Claude Opus 4.6 (claude-opus-4-6), Anthropic. February 2026.
#
# PROMPT (verbatim)
# ┌─────────────────────────────────────────────────────────────────────────┐
# │ ROLE: You are an expert in greenhouse gas emissions reporting (IPCC   │
# │ 2006 Guidelines for National Greenhouse Gas Inventories) and          │
# │ international energy statistics classifications.                       │
# │                                                                        │
# │ TASK: For each SIEC (Standard International Energy Product            │
# │ Classification) code listed below, identify the closest matching      │
# │ IPCC fuel category from the IPCC 2006 Guidelines, Volume 2 (Energy), │
# │ Chapter 2, Tables 2.2 (Default Net Calorific Values) and 2.3         │
# │ (Default CO2 Emission Factors for Stationary Combustion).             │
# │                                                                        │
# │ The SIEC codes and names below are taken verbatim from the Eurostat  │
# │ SIEC codelist (SIEC Version 1.0, as implemented by Eurostat;         │
# │ source: https://dd.eionet.europa.eu/vocabulary/eurostat/siec/view).  │
# │                                                                        │
# │ INPUT — SIEC codes to map:                                             │
# │                                                                        │
# │   Solid fossil fuels:                                                  │
# │     C0110  Anthracite                                                  │
# │     C0121  Coking coal                                                 │
# │     C0129  Other bituminous coal                                       │
# │     C0210  Sub-bituminous coal                                         │
# │     C0220  Lignite                                                     │
# │     C0311  Coke oven coke                                              │
# │     C0312  Gas coke                                                    │
# │     C0320  Patent fuel                                                 │
# │     C0330  Brown coal briquettes                                       │
# │     C0340  Coal tar                                                    │
# │                                                                        │
# │   Manufactured gases:                                                  │
# │     C0350  Coke oven gas                                               │
# │     C0360  Gas works gas                                               │
# │     C0371  Blast furnace gas                                           │
# │     C0372  Basic oxygen steel furnace gas                              │
# │     C0379  Other recovered gases                                       │
# │                                                                        │
# │   Natural gas:                                                         │
# │     G3000  Natural gas                                                 │
# │                                                                        │
# │   Oil — crude and feedstocks:                                          │
# │     O4100_TOT  Crude oil                                               │
# │     O4200      Natural gas liquids                                     │
# │     O4300      Refinery feedstocks                                     │
# │     O4500      Other hydrocarbons                                      │
# │                                                                        │
# │   Oil products:                                                        │
# │     O4610              Refinery gas                                    │
# │     O4620              Ethane                                          │
# │     O4630              Liquefied petroleum gases                       │
# │     O4640              Naphtha                                         │
# │     O4651              Aviation gasoline                               │
# │     O4652              Motor gasoline                                  │
# │     O4652XR5210B       Motor gasoline (excl. biofuel portion)          │
# │     O4653              Gasoline-type jet fuel                          │
# │     O4661              Kerosene-type jet fuel                          │
# │     O4661XR5230B       Kerosene-type jet fuel (excl. biofuel portion)  │
# │     O4669              Other kerosene                                  │
# │     O4671              Gas oil and diesel oil                          │
# │     O4671XR5220B       Gas oil and diesel oil (excl. biofuel portion)  │
# │     O4680              Fuel oil                                        │
# │     O4691              White spirit and SBP industrial spirits         │
# │     O4692              Lubricants                                      │
# │     O4693              Paraffin waxes                                  │
# │     O4694              Petroleum coke                                  │
# │     O4695              Bitumen                                         │
# │     O4699              Other oil products n.e.c.                       │
# │                                                                        │
# │   Oil shale:                                                           │
# │     S2000  Oil shale and oil sands                                     │
# │                                                                        │
# │   Peat:                                                                │
# │     P1100  Peat                                                        │
# │     P1200  Peat products                                               │
# │                                                                        │
# │   Biofuels — solid:                                                    │
# │     R5110-5150_W6000RI  Primary solid biofuels                         │
# │     R5160               Charcoal                                       │
# │                                                                        │
# │   Biofuels — liquid:                                                   │
# │     R5210B  Biogasoline (blended)                                      │
# │     R5210P  Biogasoline (pure)                                         │
# │     R5220B  Biodiesels (blended)                                       │
# │     R5220P  Biodiesels (pure)                                          │
# │     R5230B  Bio jet kerosene (blended)                                 │
# │     R5230P  Bio jet kerosene (pure)                                    │
# │     R5290   Other liquid biofuels                                      │
# │                                                                        │
# │   Biofuels — gaseous:                                                  │
# │     R5300   Biogases                                                   │
# │                                                                        │
# │ REFERENCE — IPCC 2006 Table 2.2 fuel names (use these exactly):       │
# │                                                                        │
# │   Liquid Fossil Fuels:                                                 │
# │     Crude Oil, Orimulsion, Natural Gas Liquids, Motor Gasoline,       │
# │     Aviation Gasoline, Jet Gasoline, Jet Kerosene, Other Kerosene,    │
# │     Shale Oil, Gas/Diesel Oil, Residual Fuel Oil,                     │
# │     Liquefied Petroleum Gases, Ethane, Naphtha, Bitumen, Lubricants,  │
# │     Petroleum Coke, Refinery Feedstocks, Refinery Gas,                │
# │     Paraffin Waxes, White Spirit and SBP, Other Petroleum Products    │
# │                                                                        │
# │   Solid Fossil Fuels:                                                  │
# │     Anthracite, Coking Coal, Other Bituminous Coal,                    │
# │     Sub-Bituminous Coal, Lignite, Oil Shale and Tar Sands,            │
# │     Brown Coal Briquettes, Patent Fuel,                                │
# │     Coke Oven Coke and Lignite Coke, Gas Coke, Coal Tar,              │
# │     Gas Works Gas, Coke Oven Gas, Blast Furnace Gas,                   │
# │     Oxygen Steel Furnace Gas                                           │
# │                                                                        │
# │   Gaseous Fossil Fuels:                                                │
# │     Natural Gas                                                        │
# │                                                                        │
# │   Other Fossil Fuels:                                                  │
# │     Municipal Wastes (non-biomass fraction), Industrial Wastes,        │
# │     Waste Oils, Peat                                                   │
# │                                                                        │
# │   Biomass:                                                             │
# │     Wood / Wood Waste, Sulphite lyes (Black Liquor),                   │
# │     Other Primary Solid Biomass, Charcoal, Biogasoline, Biodiesels,   │
# │     Other Liquid Biofuels, Landfill Gas, Sludge Gas, Other Biogas,    │
# │     Municipal Wastes (biomass fraction)                                │
# │                                                                        │
# │ MAPPING INSTRUCTIONS:                                                  │
# │   - Use IPCC fuel names exactly as they appear above                   │
# │   - Where a 1:1 match exists, mark mapping_quality = "exact"         │
# │   - Where the SIEC code is broader or narrower than any single IPCC  │
# │     fuel, map to the closest IPCC fuel and mark                       │
# │     mapping_quality = "approx", with a note explaining the mismatch  │
# │   - Flag products primarily used for non-energy purposes              │
# │     (lubricants, bitumen, paraffin waxes) in the notes column        │
# │                                                                        │
# │ OUTPUT FORMAT: Return an R tribble() with exactly five columns:       │
# │   - siec_code: character (use exactly the codes listed above)         │
# │   - siec_name: character (use exactly the names listed above)         │
# │   - ipcc_fuel: character (IPCC 2006 fuel name from Table 2.2/2.3)   │
# │   - mapping_quality: character ("exact" or "approx")                  │
# │   - notes: character (NA_character_ if exact; explanation if approx)  │
# └─────────────────────────────────────────────────────────────────────────┘
#
# OUTPUTS
#   - data/processed/siec_to_ipcc.RData
###############################################################################

# ====================
# Define paths -------
# ====================

if (tolower(Sys.info()[["user"]]) == "jardang") {
  REPO_DIR <- "C:/Users/jardang/Documents/inferring_emissions"
} else if (tolower(Sys.info()[["user"]]) == "jota_"){
  REPO_DIR <- "C:/Users/jota_/Documents/inferring_emissions"
} else {
  stop("Define REPO_DIR for this user.")
}
source(file.path(REPO_DIR, "paths.R"))

# ====================
# Setup --------------
# ====================

library(tibble)
library(dplyr)
library(stringr)

# =============================================================================
# SIEC -> IPCC 2006 Fuel Category Crosswalk
#
# SIEC codes/names: Eurostat SIEC codelist (SIEC v1.0)
#   https://dd.eionet.europa.eu/vocabulary/eurostat/siec/view
#
# IPCC fuel assignments: LLM-generated (Claude Opus 4.6, February 2026)
#   using the prompt above.
#
# Maps Eurostat SIEC product codes to IPCC 2006 Guidelines fuel names
# (Volume 2, Energy, Chapter 2, Tables 2.2 and 2.3).
# =============================================================================

# =============================================================================
# <<< PASTE LLM OUTPUT HERE >>>
#
# Run the prompt documented above in a fresh Claude Opus 4.6 conversation,
# then replace this placeholder with the resulting tribble().
# The output should be an R tribble with columns:
#   siec_code, siec_name, ipcc_fuel, mapping_quality, notes
# =============================================================================

siec_to_ipcc <- tribble(
  ~siec_code, ~siec_name, ~ipcc_fuel, ~mapping_quality, ~notes
  # <<< PASTE ROWS HERE >>>
)

# Clean up whitespace
siec_to_ipcc <- siec_to_ipcc %>%
  mutate(
    siec_code = str_trim(siec_code),
    ipcc_fuel = str_trim(ipcc_fuel)
  )

# ====================
# Save ---------------
# ====================

save(siec_to_ipcc, file = paste0(PROC_DATA, "/siec_to_ipcc.RData"))

cat("Saved", nrow(siec_to_ipcc), "SIEC-to-IPCC mappings to",
    paste0(PROC_DATA, "/siec_to_ipcc.RData"), "\n")
cat("Exact matches: ", sum(siec_to_ipcc$mapping_quality == "exact"), "\n")
cat("Approx matches:", sum(siec_to_ipcc$mapping_quality == "approx"), "\n")
