###############################################################################
# preprocess/13_build_siec_to_ipcc_mapping.R
#
# PURPOSE
#   Build SIEC -> IPCC fuel category mapping used to translate
#   Eurostat/energy-balance fuels into IPCC categories.
#
# HOW THIS LIST WAS PRODUCED
#   The IPCC fuel assignments were generated by prompting an LLM (Claude
#   Opus 4.6, Anthropic) in a fresh conversation with no project-specific
#   context.  The SIEC codes and names were taken verbatim from the
#   Eurostat SIEC codelist (SIEC Version 1.0, as implemented by Eurostat;
#   source: https://dd.eionet.europa.eu/vocabulary/eurostat/siec/view)
#   and embedded in the prompt so the LLM only had to supply the IPCC
#   mapping — not recall the SIEC codes from memory.
#
#   The exact prompt is reproduced below so that other researchers can
#   verify or reproduce the mapping independently.
#
# MODEL
#   Claude Opus 4.6 (claude-opus-4-6), Anthropic. February 2026.
#
# PROMPT (verbatim)
# ┌─────────────────────────────────────────────────────────────────────────┐
# │ ROLE: You are an expert in greenhouse gas emissions reporting (IPCC   │
# │ 2006 Guidelines for National Greenhouse Gas Inventories) and          │
# │ international energy statistics classifications.                       │
# │                                                                        │
# │ TASK: For each SIEC (Standard International Energy Product            │
# │ Classification) code listed below, identify the closest matching      │
# │ IPCC fuel category from the IPCC 2006 Guidelines, Volume 2 (Energy), │
# │ Chapter 2, Tables 2.2 (Default Net Calorific Values) and 2.3         │
# │ (Default CO2 Emission Factors for Stationary Combustion).             │
# │                                                                        │
# │ The SIEC codes and names below are taken verbatim from the Eurostat  │
# │ SIEC codelist (SIEC Version 1.0, as implemented by Eurostat;         │
# │ source: https://dd.eionet.europa.eu/vocabulary/eurostat/siec/view).  │
# │                                                                        │
# │ INPUT — SIEC codes to map:                                             │
# │                                                                        │
# │   Solid fossil fuels:                                                  │
# │     C0110  Anthracite                                                  │
# │     C0121  Coking coal                                                 │
# │     C0129  Other bituminous coal                                       │
# │     C0210  Sub-bituminous coal                                         │
# │     C0220  Lignite                                                     │
# │     C0311  Coke oven coke                                              │
# │     C0312  Gas coke                                                    │
# │     C0320  Patent fuel                                                 │
# │     C0330  Brown coal briquettes                                       │
# │     C0340  Coal tar                                                    │
# │                                                                        │
# │   Manufactured gases:                                                  │
# │     C0350  Coke oven gas                                               │
# │     C0360  Gas works gas                                               │
# │     C0371  Blast furnace gas                                           │
# │     C0372  Basic oxygen steel furnace gas                              │
# │     C0379  Other recovered gases                                       │
# │                                                                        │
# │   Natural gas:                                                         │
# │     G3000  Natural gas                                                 │
# │                                                                        │
# │   Oil — crude and feedstocks:                                          │
# │     O4100_TOT  Crude oil                                               │
# │     O4200      Natural gas liquids                                     │
# │     O4300      Refinery feedstocks                                     │
# │     O4500      Other hydrocarbons                                      │
# │                                                                        │
# │   Oil products:                                                        │
# │     O4610              Refinery gas                                    │
# │     O4620              Ethane                                          │
# │     O4630              Liquefied petroleum gases                       │
# │     O4640              Naphtha                                         │
# │     O4651              Aviation gasoline                               │
# │     O4652              Motor gasoline                                  │
# │     O4652XR5210B       Motor gasoline (excl. biofuel portion)          │
# │     O4653              Gasoline-type jet fuel                          │
# │     O4661              Kerosene-type jet fuel                          │
# │     O4661XR5230B       Kerosene-type jet fuel (excl. biofuel portion)  │
# │     O4669              Other kerosene                                  │
# │     O4671              Gas oil and diesel oil                          │
# │     O4671XR5220B       Gas oil and diesel oil (excl. biofuel portion)  │
# │     O4680              Fuel oil                                        │
# │     O4691              White spirit and SBP industrial spirits         │
# │     O4692              Lubricants                                      │
# │     O4693              Paraffin waxes                                  │
# │     O4694              Petroleum coke                                  │
# │     O4695              Bitumen                                         │
# │     O4699              Other oil products n.e.c.                       │
# │                                                                        │
# │   Oil shale:                                                           │
# │     S2000  Oil shale and oil sands                                     │
# │                                                                        │
# │   Peat:                                                                │
# │     P1100  Peat                                                        │
# │     P1200  Peat products                                               │
# │                                                                        │
# │   Biofuels — solid:                                                    │
# │     R5110-5150_W6000RI  Primary solid biofuels                         │
# │     R5160               Charcoal                                       │
# │                                                                        │
# │   Biofuels — liquid:                                                   │
# │     R5210B  Biogasoline (blended)                                      │
# │     R5210P  Biogasoline (pure)                                         │
# │     R5220B  Biodiesels (blended)                                       │
# │     R5220P  Biodiesels (pure)                                          │
# │     R5230B  Bio jet kerosene (blended)                                 │
# │     R5230P  Bio jet kerosene (pure)                                    │
# │     R5290   Other liquid biofuels                                      │
# │                                                                        │
# │   Biofuels — gaseous:                                                  │
# │     R5300   Biogases                                                   │
# │                                                                        │
# │ REFERENCE — IPCC 2006 Table 2.2 fuel names (use these exactly):       │
# │                                                                        │
# │   Liquid Fossil Fuels:                                                 │
# │     Crude Oil, Orimulsion, Natural Gas Liquids, Motor Gasoline,       │
# │     Aviation Gasoline, Jet Gasoline, Jet Kerosene, Other Kerosene,    │
# │     Shale Oil, Gas/Diesel Oil, Residual Fuel Oil,                     │
# │     Liquefied Petroleum Gases, Ethane, Naphtha, Bitumen, Lubricants,  │
# │     Petroleum Coke, Refinery Feedstocks, Refinery Gas,                │
# │     Paraffin Waxes, White Spirit and SBP, Other Petroleum Products    │
# │                                                                        │
# │   Solid Fossil Fuels:                                                  │
# │     Anthracite, Coking Coal, Other Bituminous Coal,                    │
# │     Sub-Bituminous Coal, Lignite, Oil Shale and Tar Sands,            │
# │     Brown Coal Briquettes, Patent Fuel,                                │
# │     Coke Oven Coke and Lignite Coke, Gas Coke, Coal Tar,              │
# │     Gas Works Gas, Coke Oven Gas, Blast Furnace Gas,                   │
# │     Oxygen Steel Furnace Gas                                           │
# │                                                                        │
# │   Gaseous Fossil Fuels:                                                │
# │     Natural Gas                                                        │
# │                                                                        │
# │   Other Fossil Fuels:                                                  │
# │     Municipal Wastes (non-biomass fraction), Industrial Wastes,        │
# │     Waste Oils, Peat                                                   │
# │                                                                        │
# │   Biomass:                                                             │
# │     Wood / Wood Waste, Sulphite lyes (Black Liquor),                   │
# │     Other Primary Solid Biomass, Charcoal, Biogasoline, Biodiesels,   │
# │     Other Liquid Biofuels, Landfill Gas, Sludge Gas, Other Biogas,    │
# │     Municipal Wastes (biomass fraction)                                │
# │                                                                        │
# │ MAPPING INSTRUCTIONS:                                                  │
# │   - Use IPCC fuel names exactly as they appear above                   │
# │   - Where a 1:1 match exists, mark mapping_quality = "exact"         │
# │   - Where the SIEC code is broader or narrower than any single IPCC  │
# │     fuel, map to the closest IPCC fuel and mark                       │
# │     mapping_quality = "approx", with a note explaining the mismatch  │
# │   - Flag products primarily used for non-energy purposes              │
# │     (lubricants, bitumen, paraffin waxes) in the notes column        │
# │                                                                        │
# │ OUTPUT FORMAT: Return an R tribble() with exactly five columns:       │
# │   - siec_code: character (use exactly the codes listed above)         │
# │   - siec_name: character (use exactly the names listed above)         │
# │   - ipcc_fuel: character (IPCC 2006 fuel name from Table 2.2/2.3)   │
# │   - mapping_quality: character ("exact" or "approx")                  │
# │   - notes: character (NA_character_ if exact; explanation if approx)  │
# └─────────────────────────────────────────────────────────────────────────┘
#
# OUTPUTS
#   - data/processed/siec_to_ipcc.RData
###############################################################################

# ====================
# Define paths -------
# ====================

if (tolower(Sys.info()[["user"]]) == "jardang") {
  REPO_DIR <- "C:/Users/jardang/Documents/inferring_emissions"
} else if (tolower(Sys.info()[["user"]]) == "jota_"){
  REPO_DIR <- "C:/Users/jota_/Documents/inferring_emissions"
} else {
  stop("Define REPO_DIR for this user.")
}
source(file.path(REPO_DIR, "paths.R"))

# ====================
# Setup --------------
# ====================

library(tibble)
library(dplyr)
library(stringr)

# =============================================================================
# SIEC -> IPCC 2006 Fuel Category Crosswalk
#
# SIEC codes/names: Eurostat SIEC codelist (SIEC v1.0)
#   https://dd.eionet.europa.eu/vocabulary/eurostat/siec/view
#
# IPCC fuel assignments: LLM-generated (Claude Opus 4.6, February 2026)
#   using the prompt above.
#
# Maps Eurostat SIEC product codes to IPCC 2006 Guidelines fuel names
# (Volume 2, Energy, Chapter 2, Tables 2.2 and 2.3).
# =============================================================================

siec_to_ipcc <- tribble(
  ~siec_code,                ~siec_name,                                    ~ipcc_fuel,                              ~mapping_quality, ~notes,

  # Solid fossil fuels
  "C0110",                   "Anthracite",                                   "Anthracite",                            "exact",          NA_character_,
  "C0121",                   "Coking coal",                                  "Coking Coal",                           "exact",          NA_character_,
  "C0129",                   "Other bituminous coal",                        "Other Bituminous Coal",                 "exact",          NA_character_,
  "C0210",                   "Sub-bituminous coal",                          "Sub-Bituminous Coal",                   "exact",          NA_character_,
  "C0220",                   "Lignite",                                      "Lignite",                               "exact",          NA_character_,
  "C0311",                   "Coke oven coke",                               "Coke Oven Coke and Lignite Coke",       "approx",         "IPCC category also includes lignite coke",
  "C0312",                   "Gas coke",                                     "Gas Coke",                              "exact",          NA_character_,
  "C0320",                   "Patent fuel",                                  "Patent Fuel",                           "exact",          NA_character_,
  "C0330",                   "Brown coal briquettes",                        "Brown Coal Briquettes",                 "exact",          NA_character_,
  "C0340",                   "Coal tar",                                     "Coal Tar",                              "exact",          NA_character_,

  # Manufactured gases
  "C0350",                   "Coke oven gas",                                "Coke Oven Gas",                         "exact",          NA_character_,
  "C0360",                   "Gas works gas",                                "Gas Works Gas",                         "exact",          NA_character_,
  "C0371",                   "Blast furnace gas",                            "Blast Furnace Gas",                     "exact",          NA_character_,
  "C0372",                   "Basic oxygen steel furnace gas",               "Oxygen Steel Furnace Gas",              "exact",          NA_character_,
  "C0379",                   "Other recovered gases",                        "Blast Furnace Gas",                     "approx",         "No direct IPCC match; mapped to Blast Furnace Gas as closest manufactured gas category",

  # Natural gas
  "G3000",                   "Natural gas",                                  "Natural Gas",                           "exact",          NA_character_,

  # Oil — crude and feedstocks
  "O4100_TOT",               "Crude oil",                                    "Crude Oil",                             "exact",          NA_character_,
  "O4200",                   "Natural gas liquids",                          "Natural Gas Liquids",                   "exact",          NA_character_,
  "O4300",                   "Refinery feedstocks",                          "Refinery Feedstocks",                   "exact",          NA_character_,
  "O4500",                   "Other hydrocarbons",                           "Other Petroleum Products",              "approx",         "SIEC is a broad residual category; mapped to IPCC residual liquid fossil fuel",

  # Oil products
  "O4610",                   "Refinery gas",                                 "Refinery Gas",                          "exact",          NA_character_,
  "O4620",                   "Ethane",                                       "Ethane",                                "exact",          NA_character_,
  "O4630",                   "Liquefied petroleum gases",                    "Liquefied Petroleum Gases",             "exact",          NA_character_,
  "O4640",                   "Naphtha",                                      "Naphtha",                               "exact",          NA_character_,
  "O4651",                   "Aviation gasoline",                            "Aviation Gasoline",                     "exact",          NA_character_,
  "O4652",                   "Motor gasoline",                               "Motor Gasoline",                        "exact",          NA_character_,
  "O4652XR5210B",            "Motor gasoline (excl. biofuel portion)",       "Motor Gasoline",                        "approx",         "Fossil portion only; biofuel portion excluded by SIEC definition",
  "O4653",                   "Gasoline-type jet fuel",                       "Jet Gasoline",                          "exact",          NA_character_,
  "O4661",                   "Kerosene-type jet fuel",                       "Jet Kerosene",                          "exact",          NA_character_,
  "O4661XR5230B",            "Kerosene-type jet fuel (excl. biofuel portion)", "Jet Kerosene",                        "approx",         "Fossil portion only; biofuel portion excluded by SIEC definition",
  "O4669",                   "Other kerosene",                               "Other Kerosene",                        "exact",          NA_character_,
  "O4671",                   "Gas oil and diesel oil",                       "Gas/Diesel Oil",                        "exact",          NA_character_,
  "O4671XR5220B",            "Gas oil and diesel oil (excl. biofuel portion)", "Gas/Diesel Oil",                      "approx",         "Fossil portion only; biofuel portion excluded by SIEC definition",
  "O4680",                   "Fuel oil",                                     "Residual Fuel Oil",                     "exact",          NA_character_,
  "O4691",                   "White spirit and SBP industrial spirits",      "White Spirit and SBP",                  "exact",          NA_character_,
  "O4692",                   "Lubricants",                                   "Lubricants",                            "exact",          "Primarily non-energy use",
  "O4693",                   "Paraffin waxes",                               "Paraffin Waxes",                        "exact",          "Primarily non-energy use",
  "O4694",                   "Petroleum coke",                               "Petroleum Coke",                        "exact",          NA_character_,
  "O4695",                   "Bitumen",                                      "Bitumen",                               "exact",          "Primarily non-energy use",
  "O4699",                   "Other oil products n.e.c.",                    "Other Petroleum Products",              "exact",          NA_character_,

  # Oil shale
  "S2000",                   "Oil shale and oil sands",                      "Oil Shale and Tar Sands",               "exact",          NA_character_,

  # Peat
  "P1100",                   "Peat",                                         "Peat",                                  "exact",          NA_character_,
  "P1200",                   "Peat products",                                "Peat",                                  "approx",         "IPCC has single Peat category; peat products (briquettes etc.) mapped here",

  # Biofuels — solid
  "R5110-5150_W6000RI",      "Primary solid biofuels",                       "Wood / Wood Waste",                     "approx",         "SIEC aggregate covers wood, vegetal waste, animal waste etc.; Wood / Wood Waste is the dominant component. Other Primary Solid Biomass may also apply",
  "R5160",                   "Charcoal",                                     "Charcoal",                              "exact",          NA_character_,

  # Biofuels — liquid
  "R5210B",                  "Biogasoline (blended)",                        "Biogasoline",                           "approx",         "SIEC refers to biofuel portion in blended gasoline",
  "R5210P",                  "Biogasoline (pure)",                           "Biogasoline",                           "exact",          NA_character_,
  "R5220B",                  "Biodiesels (blended)",                         "Biodiesels",                            "approx",         "SIEC refers to biofuel portion in blended diesel",
  "R5220P",                  "Biodiesels (pure)",                            "Biodiesels",                            "exact",          NA_character_,
  "R5230B",                  "Bio jet kerosene (blended)",                   "Other Liquid Biofuels",                 "approx",         "No specific IPCC bio jet kerosene category; mapped to Other Liquid Biofuels",
  "R5230P",                  "Bio jet kerosene (pure)",                      "Other Liquid Biofuels",                 "approx",         "No specific IPCC bio jet kerosene category; mapped to Other Liquid Biofuels",
  "R5290",                   "Other liquid biofuels",                        "Other Liquid Biofuels",                 "exact",          NA_character_,

  # Biofuels — gaseous
  "R5300",                   "Biogases",                                     "Other Biogas",                          "approx",         "SIEC aggregates all biogases; IPCC distinguishes Landfill Gas, Sludge Gas, Other Biogas. Mapped to Other Biogas as broadest category"
)

# Clean up whitespace
siec_to_ipcc <- siec_to_ipcc %>%
  mutate(
    siec_code = str_trim(siec_code),
    ipcc_fuel = str_trim(ipcc_fuel)
  )

# ====================
# Save ---------------
# ====================

save(siec_to_ipcc, file = paste0(PROC_DATA, "/siec_to_ipcc.RData"))

cat("Saved", nrow(siec_to_ipcc), "SIEC-to-IPCC mappings to",
    paste0(PROC_DATA, "/siec_to_ipcc.RData"), "\n")
cat("Exact matches: ", sum(siec_to_ipcc$mapping_quality == "exact"), "\n")
cat("Approx matches:", sum(siec_to_ipcc$mapping_quality == "approx"), "\n")
