###############################################################################
# preprocess/18_build_cn8_fossil_fuel_list.R
#
# PURPOSE
#   Define the list of CN8 product codes from Chapter 27 that correspond to
#   fossil fuels combustible in stationary industrial installations. Used
#   downstream by build_auxiliary_tables.R to define the "strict" fuel filter.
#
# HOW THIS LIST WAS PRODUCED
#   The classification was generated by prompting an LLM (Claude Opus 4.6,
#   Anthropic) in a fresh conversation with no project-specific context.
#   The exact prompt is reproduced below so that other researchers can
#   verify or reproduce the list independently.
#
# MODEL
#   Claude Opus 4.6 (claude-opus-4-6), Anthropic. February 2026.
#
# PROMPT (verbatim)
# ┌─────────────────────────────────────────────────────────────────────────┐
# │ ROLE: You are an expert in international trade classification systems  │
# │ (HS/CN nomenclature) and greenhouse gas emissions reporting (IPCC,    │
# │ EU ETS).                                                              │
# │                                                                       │
# │ TASK: From the complete list of 8-digit Combined Nomenclature (CN8)  │
# │ product codes from Chapter 27 below, identify which codes correspond │
# │ to fossil fuels that could be combusted for energy in stationary     │
# │ installations (e.g. boilers, furnaces, kilns, CHP plants, backup    │
# │ generators).                                                          │
# │                                                                       │
# │ The CN8 codes and descriptions below are taken from the 2022 EU      │
# │ Combined Nomenclature (Commission Implementing Regulation (EU)       │
# │ 2021/1832, Annex I).                                                 │
# │                                                                       │
# │ INPUT — All CN8 codes in Chapter 27:                                  │
# │                                                                       │
# │   2701 — Coal; briquettes, ovoids and similar solid fuels:           │
# │     27011100  Anthracite                                              │
# │     27011210  Coking coal                                             │
# │     27011290  Other bituminous coal                                   │
# │     27011900  Other coal (incl. sub-bituminous)                      │
# │     27012000  Briquettes, ovoids and similar solid fuels from coal   │
# │   2702 — Lignite:                                                    │
# │     27021000  Lignite, not agglomerated                              │
# │     27022000  Agglomerated lignite                                   │
# │   2703 — Peat:                                                       │
# │     27030000  Peat (including peat litter)                           │
# │   2704 — Coke and semi-coke:                                         │
# │     27040010  Coke and semi-coke of coal                             │
# │     27040030  Coke and semi-coke of lignite                          │
# │     27040090  Other coke and semi-coke (incl. retort carbon)         │
# │   2705 — Coal gas, water gas, producer gas:                          │
# │     27050000  Coal gas, water gas, producer gas, similar gases       │
# │   2706 — Tar:                                                        │
# │     27060000  Tar from coal, lignite, peat; other mineral tars       │
# │   2707 — Oils from high-temperature coal tar distillation:           │
# │     27071000  Benzol (benzene)                                       │
# │     27072000  Toluol (toluene)                                       │
# │     27073000  Xylol (xylenes)                                       │
# │     27074000  Naphthalene                                            │
# │     27075000  Other aromatic hydrocarbon mixtures                    │
# │     27079100  Creosote oils                                          │
# │     27079911  Crude light oils (>= 90% distils at 200°C)            │
# │     27079919  Other crude light oils                                 │
# │     27079920  Sulphuretted toppings; anthracene                      │
# │     27079950  Basic products                                         │
# │     27079980  Phenols                                                │
# │     27079991  Products for manufacture of heading 2803               │
# │     27079999  Other products of coal tar distillation                │
# │   2708 — Pitch and pitch coke:                                       │
# │     27081000  Pitch from coal tar or mineral tars                    │
# │     27082000  Pitch coke                                             │
# │   2709 — Crude petroleum oils:                                       │
# │     27090010  Natural gas condensates                                │
# │     27090090  Other crude petroleum oils                             │
# │   2710 — Petroleum oils (not crude), preparations, waste oils:       │
# │     27101211  Light oils for specific process                        │
# │     27101215  Light oils for chemical transformation                 │
# │     27101221  White spirit                                           │
# │     27101225  Other special spirits                                  │
# │     27101231  Aviation spirit (avgas)                                │
# │     27101241  Motor spirit, RON < 95                                 │
# │     27101245  Motor spirit, RON 95-98                                │
# │     27101249  Motor spirit, RON >= 98                                │
# │     27101250  Motor spirit, leaded                                   │
# │     27101270  Spirit type jet fuel                                   │
# │     27101290  Other light oils and preparations                      │
# │     27101911  Medium oils for specific process                       │
# │     27101915  Medium oils for chemical transformation                │
# │     27101921  Jet fuel (kerosene type)                               │
# │     27101925  Other kerosene                                         │
# │     27101929  Other medium oils and preparations                     │
# │     27101931  Gas oils for specific process                          │
# │     27101935  Gas oils for chemical transformation                   │
# │     27101943  Gas oils, sulphur <= 0.001%                            │
# │     27101946  Gas oils, sulphur > 0.001% to 0.002%                  │
# │     27101947  Gas oils, sulphur > 0.002% to 0.1%                    │
# │     27101948  Gas oils, sulphur > 0.1%                               │
# │     27101951  Fuel oils for specific process                         │
# │     27101955  Fuel oils for chemical transformation                  │
# │     27101962  Fuel oils, sulphur <= 0.1%                             │
# │     27101966  Fuel oils, sulphur > 0.1% to 0.5%                     │
# │     27101967  Fuel oils, sulphur > 0.5%                              │
# │     27101971  Lubricating oils for specific process                  │
# │     27101975  Lubricating oils for chemical transformation           │
# │     27101981  Motor/compressor/turbine lube oils                     │
# │     27101983  Hydraulic oils                                         │
# │     27101985  White oils, liquid paraffin                            │
# │     27101987  Gear oils and reductor oils                            │
# │     27101991  Metal-working compounds, mould-release oils            │
# │     27101993  Electrical insulating oils                             │
# │     27101999  Other lubricating oils                                 │
# │     27102011  Gas oils w/ biodiesel, sulphur <= 0.001%              │
# │     27102016  Gas oils w/ biodiesel, sulphur > 0.001% to 0.1%      │
# │     27102019  Gas oils w/ biodiesel, sulphur > 0.1%                 │
# │     27102032  Fuel oils w/ biodiesel, sulphur <= 0.5%               │
# │     27102038  Fuel oils w/ biodiesel, sulphur > 0.5%                │
# │     27102090  Other petroleum oils w/ biodiesel                      │
# │     27109100  Waste oils containing PCBs/PCTs/PBBs                  │
# │     27109900  Other waste oils                                       │
# │   2711 — Petroleum gases and gaseous hydrocarbons:                   │
# │     27111100  LNG                                                    │
# │     27111211  Propane (>= 99%), for power/heating                   │
# │     27111219  Propane (>= 99%), other purposes                      │
# │     27111291  Propane (90-99%), for specific process                 │
# │     27111293  Propane (90-99%), for chemical transformation          │
# │     27111294  Propane (90-99%), other purposes                       │
# │     27111297  Other propane                                          │
# │     27111310  Butanes, for specific process                          │
# │     27111330  Butanes, for chemical transformation                   │
# │     27111391  Butanes (90-95%), other purposes                       │
# │     27111397  Other butanes                                          │
# │     27111400  Ethylene, propylene, butylene, butadiene               │
# │     27111900  Other LPG                                              │
# │     27112100  Natural gas in gaseous state                           │
# │     27112900  Other gaseous hydrocarbons                             │
# │   2712 — Petroleum jelly, paraffin wax, mineral waxes:              │
# │     27121010  Crude petroleum jelly                                  │
# │     27121090  Other petroleum jelly                                  │
# │     27122010  Synthetic paraffin wax                                 │
# │     27122090  Other paraffin wax                                     │
# │     27129011  Crude ozokerite, lignite/peat wax                     │
# │     27129019  Other ozokerite, lignite/peat wax                     │
# │     27129031  Crude mineral waxes, for specific process              │
# │     27129033  Crude mineral waxes, for chemical transformation       │
# │     27129039  Crude mineral waxes, other purposes                    │
# │     27129091  Blends of 1-alkenes                                    │
# │     27129099  Other mineral waxes                                    │
# │   2713 — Petroleum coke, petroleum bitumen, other residues:         │
# │     27131100  Petroleum coke, not calcined                           │
# │     27131200  Petroleum coke, calcined                               │
# │     27132000  Petroleum bitumen                                      │
# │     27139010  Other residues for manufacture of heading 2803         │
# │     27139090  Other residues of petroleum oils                       │
# │   2714 — Bituminous minerals, natural bitumen:                      │
# │     27141000  Bituminous or oil-shale and tar sands                  │
# │     27149000  Other natural bitumen and natural asphalt              │
# │   2715 — Bituminous mixtures:                                        │
# │     27150000  Bituminous mixtures                                    │
# │   2716 — Electrical energy:                                          │
# │     27160000  Electrical energy                                      │
# │                                                                       │
# │ CLASSIFICATION CRITERIA:                                              │
# │                                                                       │
# │ Include codes for:                                                    │
# │   - Solid fossil fuels: coal, lignite, coke, semi-coke, briquettes  │
# │   - Liquid fossil fuels: crude oil, fuel oils, gas oils / diesel,   │
# │     kerosene (heating), naphtha, LPG, petroleum coke, and other     │
# │     petroleum products burned for heat or power in STATIONARY        │
# │     installations                                                     │
# │   - Gaseous fossil fuels: natural gas, petroleum gases (propane,    │
# │     butane, ethylene, etc.) in gaseous or liquefied form             │
# │   - Peat and peat products                                           │
# │                                                                       │
# │ Exclude codes for:                                                    │
# │   - Electricity (2716)                                                │
# │   - Transport fuels: motor gasoline / motor spirit (27101231–        │
# │     27101250), aviation gasoline (27101231), jet fuels — both        │
# │     gasoline-type (27101270) and kerosene-type (27101921)            │
# │   - Products primarily NOT fuels: lubricating oils, greases,         │
# │     paraffin wax, petroleum jelly, bitumen / asphalt, mineral waxes │
# │   - Mineral tar pitch (27081000) — used as binder, not fuel          │
# │                                                                       │
# │ Edge cases: If a product (e.g. white spirit, naphtha grades, waste  │
# │ oils) is sometimes burned for energy but primarily used as solvent   │
# │ or feedstock, INCLUDE it and note "[EDGE CASE: ...]" in the         │
# │ description.                                                          │
# │                                                                       │
# │ OUTPUT FORMAT: Return an R tribble() with exactly two columns:       │
# │   - cn_code: character, 8-digit CN code (e.g., "27011100")          │
# │   - description: character, CN 2022 product description (append     │
# │     edge-case notes in square brackets where applicable)             │
# │                                                                       │
# │ Group codes by HS4 heading with a brief R comment above each group. │
# │ Do not include any codes outside Chapter 27.                          │
# └─────────────────────────────────────────────────────────────────────────┘
#
# OUTPUTS
#   - data/processed/cn8digit_codes_for_fossil_fuels.RData
###############################################################################

# ====================
# Define paths -------
# ====================

if (tolower(Sys.info()[["user"]]) == "jardang") {
  REPO_DIR <- "C:/Users/jardang/Documents/inferring_emissions"
} else if (tolower(Sys.info()[["user"]]) == "jota_"){
  REPO_DIR <- "C:/Users/jota_/Documents/inferring_emissions"
} else {
  stop("Define REPO_DIR for this user.")
}
source(file.path(REPO_DIR, "paths.R"))

# ====================
# Setup --------------
# ====================

library(tibble)

# =============================================================================
# CN8 codes (2022) — Chapter 27 fossil fuels combustible in stationary
# installations (boilers, furnaces, kilns, CHP, backup generators)
#
# Source: Commission Implementing Regulation (EU) 2021/1832, Annex I
#         (Combined Nomenclature applicable from 1 January 2022)
#
# Inclusion criteria : solid, liquid & gaseous fossil fuels; peat
# Exclusion criteria : electricity (2716), transport fuels (motor gasoline,
#                      aviation gasoline, jet fuels), lubricating oils &
#                      greases, paraffin wax, petroleum jelly,
#                      bitumen/asphalt, mineral tar
# Edge-case policy   : inclusive — borderline products noted in description
# =============================================================================

# =============================================================================
# <<< PASTE LLM OUTPUT HERE >>>
#
# Run the prompt documented above in a fresh Claude Opus 4.6 conversation,
# then replace this placeholder with the resulting tribble().
# The output should be an R tribble with columns: cn_code, description
# =============================================================================

cn8digit_codes_for_fossil_fuels <- tribble(
  ~cn_code,     ~description
  # <<< PASTE ROWS HERE >>>
)

# ====================
# Save ---------------
# ====================

save(cn8digit_codes_for_fossil_fuels,
     file = paste0(PROC_DATA, "/cn8digit_codes_for_fossil_fuels.RData"))

cat("Saved", nrow(cn8digit_codes_for_fossil_fuels), "CN8 codes to",
    paste0(PROC_DATA, "/cn8digit_codes_for_fossil_fuels.RData"), "\n")
